[project]
name = "hex-hexes"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "mathjax>=0.1.2",
    "matplotlib>=3.10.1",
    "numpy>=2.2.4",
    "sympy>=1.13.3",
    "tqdm>=4.67.1",
]

[tool.pyright]
reportOperatorIssue = "none"
